apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfigdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DockerWebApiSample
  template:
    metadata:
      labels:
        app: DockerWebApiSample
    spec:
      containers:
      - name: dockersamplerepos
        image: samplectr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn1

---
apiVersion: v1
kind: Service
metadata:
  name: dockerwebapisample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DockerWebApiSample
